export const ALL_ORDERS_WS_CONNECTION_START = "ALL_ORDERS_WS_CONNECTION_START";
export const ALL_ORDERS_WS_CONNECTION_SUCCESS =
  "ALL_ORDERS_WS_CONNECTION_SUCCESS";
export const ALL_ORDERS_WS_CONNECTION_ERROR = "ALL_ORDERS_WS_CONNECTION_ERROR";
export const ALL_ORDERS_WS_CONNECTION_CLOSED =
  "ALL_ORDERS_WS_CONNECTION_CLOSED";
export const ALL_ORDERS_WS_GET_MESSAGE = "ALL_ORDERS_WS_GET_MESSAGE";
export const ALL_ORDERS_WS_SEND_MESSAGE = "ALL_ORDERS_WS_SEND_MESSAGE";
export const ALL_ORDERS_WS_CONNECTION_STOP = "ALL_ORDERS_WS_CONNECTION_STOP"

export const wsConnectAllOrders = (url) => {
  return {
    type: ALL_ORDERS_WS_CONNECTION_START,
    payload: url,
  };
};

export const wsDisconnectAllOrders = () => {
  return {
    type: ALL_ORDERS_WS_CONNECTION_STOP,
  };
};