export const USER_ORDERS_WS_CONNECTION_START =
  "USER_ORDERS_WS_CONNECTION_START";
export const USER_ORDERS_WS_CONNECTION_SUCCESS =
  "USER_ORDERS_WS_CONNECTION_SUCCESS";
export const USER_ORDERS_WS_CONNECTION_ERROR =
  "USER_ORDERS_WS_CONNECTION_ERROR";
export const USER_ORDERS_WS_CONNECTION_CLOSED =
  "USER_ORDERS_WS_CONNECTION_CLOSED";
export const USER_ORDERS_WS_GET_MESSAGE = "USER_ORDERS_WS_GET_MESSAGE";
export const USER_ORDERS_WS_SEND_MESSAGE = "USER_ORDERS_WS_SEND_MESSAGE";
export const USER_ORDERS_WS_CONNECTION_STOP = "USER_ORDERS_WS_CONNECTION_STOP"

export const wsConnectUserOrders = (url) => {
  return {
    type: USER_ORDERS_WS_CONNECTION_START,
    payload: url,
  };
};

export const wsDisconnectUserOrders = () => {
  return {
    type: USER_ORDERS_WS_CONNECTION_STOP,
  };
};